# Generated by Django 4.2.22 on 2025-10-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0102_alter_impactedpackage_affecting_vers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="pipeline_version",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
